import React from 'react';
import { ScrollView, StyleSheet, View } from 'react-native';
import { ActivityIndicator, Button, Dialog, Portal, Text } from 'react-native-paper';

export default function WeeklyMissionDialog({ visible, onDismiss, summary, loading, error, onRetry, onAction, tab, onTabChange }) {
  const renderContent = () => {
    if (loading) return <View style={styles.state}><ActivityIndicator color="#FF7A18" /><Text>Loading your weekly mission…</Text></View>;
    if (error) return <View style={styles.state}><Text style={styles.stateTitle}>We couldn’t load your mission.</Text><Button mode="contained" onPress={onRetry}>Try again</Button></View>;
    if (!summary) return <View style={styles.state}><Text style={styles.stateTitle}>No weekly mission is available right now.</Text><Text style={styles.muted}>Check back after the next weekly reset.</Text></View>;
    if (tab === 'rewards') return <View style={styles.content}><Text style={styles.heading}>Rewards</Text><Text style={styles.sectionTitle}>{summary.reward.title}</Text><Text style={styles.body}>{summary.reward.detail}</Text><Text style={styles.muted}>Your activity still updates automatically while this weekly loop is active.</Text></View>;
    if (tab === 'how') return <View style={styles.content}><Text style={styles.heading}>How it works</Text><Text style={styles.body}>Weekly missions give you a short set of BuffaGo activities to complete each week. Progress updates automatically as you rate wings, share moments, invite friends, and visit crawl stops.</Text><Text style={styles.body}>{summary.resetCopy}</Text><Text style={styles.body}>Only activity completed during the current weekly period counts.</Text></View>;
    const next = summary.nextMission;
    return <View style={styles.content}><Text style={styles.heading}>Weekly Mission</Text><Text style={styles.muted}>Complete these four goals before the weekly reset.</Text><Text style={styles.progress}>{summary.completedCount} of {summary.totalCount} goals complete</Text>{summary.items.map((item) => <View key={item.key} style={styles.task}><View style={styles.taskCopy}><Text style={styles.taskLabel}>{item.complete ? '✓ ' : ''}{item.label}</Text></View><Text style={styles.taskProgress}>{item.current}/{item.target}</Text></View>)}<Text style={styles.reset}>{summary.resetCopy}</Text>{next ? <Button mode="contained" buttonColor="#FF7A18" onPress={() => onAction(next)}>{next.actionLabel}</Button> : <Text style={styles.complete}>All weekly goals are complete.</Text>}</View>;
  };
  return <Portal><Dialog visible={visible} onDismiss={onDismiss} style={styles.dialog} dismissable={!loading}><Dialog.Title>Weekly Mission</Dialog.Title><Dialog.Content style={styles.dialogContent}><View style={styles.tabs}>{[['active', 'Active'], ['rewards', 'Rewards'], ['how', 'How it works']].map(([key, label]) => <Button key={key} compact mode={tab === key ? 'contained-tonal' : 'text'} onPress={() => onTabChange(key)}>{label}</Button>)}</View><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>{renderContent()}</ScrollView></Dialog.Content><Dialog.Actions><Button onPress={onDismiss}>Done</Button></Dialog.Actions></Dialog></Portal>;
}

const styles = StyleSheet.create({
  dialog: { maxHeight: '84%', backgroundColor: '#24201E' }, dialogContent: { paddingBottom: 0 }, tabs: { flexDirection: 'row', gap: 4, marginBottom: 8 }, scroll: { paddingBottom: 8 }, content: { gap: 14 }, state: { minHeight: 180, justifyContent: 'center', alignItems: 'center', gap: 14 }, stateTitle: { fontSize: 17, fontWeight: '800', textAlign: 'center' }, heading: { fontSize: 22, fontWeight: '900' }, sectionTitle: { fontSize: 18, fontWeight: '800' }, body: { lineHeight: 21 }, muted: { opacity: 0.72, lineHeight: 20 }, progress: { fontWeight: '900', color: '#FFB36F' }, task: { minHeight: 48, paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: 'rgba(255,255,255,0.2)', flexDirection: 'row', alignItems: 'center', gap: 12 }, taskCopy: { flex: 1 }, taskLabel: { fontSize: 16, fontWeight: '700' }, taskProgress: { fontWeight: '900', color: '#FFB36F' }, reset: { opacity: 0.75, lineHeight: 19 }, complete: { color: '#A8E6A3', fontWeight: '800' },
});
