import {before,test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {startDisposablePostgres,fixture,query,session,observeBlocked,ids,asUser} from '../../scripts/phase7b25-postgres.mjs';
import {frozenBytes} from '../../scripts/phase7b3b-feature-executor.mjs';

const evidence=await readFile(new URL('../../../docs/buffago-production-account-rpc-evidence-2026-10-10.md',import.meta.url),'utf8');
const definition=evidence.match(/CREATE OR REPLACE FUNCTION public\.delete_account_data\([\s\S]*?AS \$function\$[\s\S]*?\$function\$/)[0]+';';
// The supplied evidence explicitly normalizes line endings. Restore CRLF:
// this reproduces the actual reported production prosrc MD5 exactly.
const actual=definition.replaceAll('\r\n','\n').replaceAll('\n','\r\n');
assert.equal(createHash('md5').update(actual.match(/AS \$function\$([\s\S]*?)\$function\$/)[1]).digest('hex'),'4f108f4b39ec1d613fd5b1ba6be97c82');
const bootstrap=new URL('./fixtures/phase7b3a-production-shaped-bootstrap.sql',import.meta.url);
const mediaSource=await readFile(new URL('../../supabase/migrations/20260729121000_wing_shots_security_rpc.sql',import.meta.url),'utf8');
const pseudonym=mediaSource.match(/create or replace function public\.wing_apply_owner_pseudonymization\(\)[\s\S]*?as \$\$([\s\S]*?)\$\$;/);
assert.equal(createHash('md5').update(pseudonym[1]).digest('hex'),'de76b9c0f76f833db3712676d0cc1b60');
before(async()=>{await startDisposablePostgres();await query('buffago_phase7b25','create role supabase_auth_admin nologin;create role supabase_storage_admin nologin;');});
async function fresh(feature=true){const db=await fixture({bootstrap,migration:false});await query(db,`
-- Reduced social prerequisite must work before feature tables exist as well.
-- This dependency is synthetic, not a recovered production implementation.
create or replace function public.can_user_appear_socially(uuid) returns boolean language plpgsql as $$begin return true;end;$$;
create or replace function public."Badge_Add_Rating_Milestones"() returns trigger language plpgsql security definer set search_path=public as $$begin return new;end;$$;
create or replace function public.flag_referral_account_deletion() returns trigger language plpgsql security definer set search_path=pg_catalog as $$begin return old;end;$$;
alter table public.crawls add column user_id uuid references auth.users(id) on delete cascade;
update public.crawls set user_id='${ids.user}';
create table public.user_preferences(user_id uuid primary key references auth.users(id) on delete cascade, preference text);
insert into public.user_preferences values('${ids.user}','fixture');
${actual}
revoke execute on function public.delete_account_data(uuid) from public,anon,authenticated;
grant execute on function public.delete_account_data(uuid) to service_role;
${pseudonym[0]}
`);if(feature)await query(db,(await frozenBytes()).sql);assert.equal(await query(db,"select md5(prosrc)||':'||md5(coalesce(proconfig::text,''))||':'||prosecdef||':'||pg_get_userbyid(proowner) from pg_proc where oid='public.delete_account_data(uuid)'::regprocedure"),'4f108f4b39ec1d613fd5b1ba6be97c82:dcd2abd514173991611a622e71d06e6f:true:postgres');return db;}
const rpc=`set role service_role;select public.delete_account_data(p_user_id=>'${ids.user}');reset role;`;
const authDelete=`delete from auth.users where id='${ids.user}'`;
const rate=`insert into public.destination_ratings(id,user_id,destination_id,crawl_id) values('${ids.rating}','${ids.user}','${ids.destination}','${ids.crawl}')`;
const vote=(who=ids.user,value=1)=>`${asUser(who)}insert into public.wing_jury_votes(user_id,submission_id,vote) values('${who}','${ids.photo}',${value});reset role;`;
async function saved(db){await query(db,`${asUser(ids.user)}insert into public.user_destination_favorites values('${ids.user}','${ids.destination}',now());insert into public.user_want_to_try values('${ids.user}','${ids.otherDestination}',now());reset role;`);}
const countSQL=`select like_count||','||neutral_count||','||dislike_count from public.wing_jury_photo_vote_counts where submission_id='${ids.photo}'`;

test('exact production RPC followed by Auth deletion removes feature ownership and decrements counts',async()=>{const db=await fresh();await query(db,rate);await saved(db);await query(db,vote()+vote(ids.other,0)+vote(ids.third,-1));await query(db,rpc);assert.equal(await query(db,`select count(*) from public.destination_ratings where user_id='${ids.user}'`),'0');assert.equal(await query(db,'select count(*) from public.user_destination_favorites'),'0');assert.equal(await query(db,'select count(*) from public.user_want_to_try'),'1');await query(db,authDelete);for(const table of ['user_destination_favorites','user_want_to_try','wing_jury_votes'])assert.equal(await query(db,`select count(*) from public.${table} where user_id='${ids.user}'`),'0');assert.equal(await query(db,countSQL),'0,1,1');assert.equal(await query(db,'select count(*) from public.wing_media_photo_votes'),'1');assert.equal(await query(db,'select like_count from public.wing_media_submissions'),'9');assert.equal(await query(db,'select count(*) from public.user_preferences'),'0');});
test('linked-rating RESTRICT failure and old data atomicity are identical before and after feature SQL',async()=>{for(const feature of [false,true]){const db=await fresh(feature);await query(db,rate+`;update public.wing_media_submissions set rating_id='${ids.rating}'`);if(feature)await saved(db);await assert.rejects(query(db,rpc),/23503/);assert.equal(await query(db,`select count(*) from public.destination_ratings where user_id='${ids.user}'`),'1');assert.equal(await query(db,'select count(*) from public.crawls'),'2');assert.equal(await query(db,'select count(*) from public.user_preferences'),'1');assert.equal(await query(db,`select count(*) from auth.users where id='${ids.user}'`),'1');if(feature)assert.equal(await query(db,'select count(*) from public.user_destination_favorites'),'1');}});
test('Auth retry after successful RPC and saved writes between phases leave no feature data',async()=>{const db=await fresh();await query(db,rate);await saved(db);await query(db,rpc);await query(db,rpc);await query(db,`${asUser(ids.user)}insert into public.user_want_to_try values('${ids.user}','${ids.destination}',now());reset role;`);await query(db,authDelete);await query(db,authDelete);assert.equal(await query(db,'select count(*) from public.user_want_to_try'),'0');assert.equal(await query(db,'select count(*) from public.user_destination_favorites'),'0');});
test('vote-first and Auth-delete-first races serialize with correct surviving counts',async()=>{for(const deleteFirst of [false,true]){const db=await fresh();await query(db,vote(ids.other,0));await query(db,rpc);const holder=session(db,'split-holder');try{await holder.execute('begin;'+(deleteFirst?authDelete:vote()));const pending=query(db,deleteFirst?vote():authDelete,'split-waiter').then(value=>({value}),error=>({error}));await observeBlocked(db,'split-waiter');await holder.execute('commit');const result=await pending;if(deleteFirst)assert.ok(result.error,'Deleted voter must be refused');else assert.ifError(result.error);assert.equal(await query(db,`select count(*) from public.wing_jury_votes where user_id='${ids.user}'`),'0');assert.equal(await query(db,countSQL),'0,1,0');}finally{await holder.close();}}});
test('media parent deletion cascades only feature votes/counts and preserves existing RESTRICT boundary',async()=>{const db=await fresh();await query(db,vote());await query(db,`insert into public.wing_submission_state_transitions(fixture_id,submission_id) values('${ids.rating}','${ids.photo}')`);await assert.rejects(query(db,`delete from public.wing_media_submissions where id='${ids.photo}'`),/23503/);assert.equal(await query(db,countSQL),'1,0,0');await query(db,'delete from public.wing_submission_state_transitions');await query(db,`delete from public.wing_media_submissions where id='${ids.photo}'`);assert.equal(await query(db,'select count(*) from public.wing_jury_votes'),'0');assert.equal(await query(db,'select count(*) from public.wing_jury_photo_vote_counts'),'0');});
test('feature SQL does not add Storage/upload capability or change existing upload/media definitions',async()=>{const db=await fresh(false);const snapshot=`select jsonb_build_object('storage_relations',(select jsonb_agg(to_jsonb(c) order by c.oid) from pg_class c where c.relnamespace='storage'::regnamespace),'storage_policies',(select jsonb_agg(to_jsonb(p) order by p.oid) from pg_policy p join pg_class c on c.oid=p.polrelid where c.relnamespace='storage'::regnamespace),'old_media_constraints',(select jsonb_agg(to_jsonb(c) order by c.oid) from pg_constraint c where c.conrelid in ('public.wing_media_submissions'::regclass,'public.destination_ratings'::regclass)),'media_rows',(select jsonb_agg(to_jsonb(m)) from public.wing_media_submissions m),'objects',(select jsonb_agg(to_jsonb(o)) from storage.objects o),'rpc',(select to_jsonb(p) from pg_proc p where oid='public.delete_account_data(uuid)'::regprocedure))`;
const before=await query(db,snapshot);await query(db,(await frozenBytes()).sql);assert.equal(await query(db,snapshot),before);const sql=(await frozenBytes()).sql;assert.doesNotMatch(sql,/create\s+(?:or\s+replace\s+)?function\s+(?:public\.)?(?:reserve_wing_submission_upload|finalize_wing_submission_upload|delete_account_data)\s*\(/i);assert.doesNotMatch(sql,/grant\s+[^;]*(?:insert|update|delete)[^;]*\bon\s+(?:table\s+)?storage\./i);});
test('media-owner deletion retains existing objects identically and makes retained Jury media ineligible',async()=>{for(const feature of [false,true]){const db=await fresh(feature);const paths=await query(db,'select jsonb_agg(to_jsonb(o)) from storage.objects o');if(feature)await query(db,vote(ids.other,1)+vote(ids.user,0));await query(db,`set role service_role;select public.delete_account_data('${ids.other}');reset role;delete from auth.users where id='${ids.other}';`);assert.equal(await query(db,'select user_id is null and owner_deleted_at is not null from public.wing_media_submissions'),'t');assert.equal(await query(db,'select jsonb_agg(to_jsonb(o)) from storage.objects o'),paths);if(feature){assert.equal(await query(db,countSQL),'0,1,0');assert.equal(await query(db,`select public.is_public_wing_jury_photo('${ids.photo}')`),'f');assert.equal(await query(db,`select count(*) from public.wing_jury_votes where user_id='${ids.other}'`),'0');}}});
