import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const reasons = [['poor_media_quality','Poor media quality'],['inappropriate_content','Inappropriate content'],['not_related_to_rating','Not clearly related to the rating'],['duplicate_submission','Duplicate submission'],['copyright_or_ownership','Copyright or ownership concern'],['restaurant_or_attribution','Restaurant or attribution issue'],['other','Other']];
const tabs = [['pending','Pending Review'],['approved','Approved Queue'],['rejected','Rejected'],['posted','Posted / History']];
const statusForTab = (tab, item) => tab === 'pending' ? item.status === 'in_review' : tab === 'approved' ? item.status === 'approved' && !item.featured_at : tab === 'rejected' ? item.status === 'rejected' : item.status === 'posted' || item.featured_at;
const formatDate = (value) => value ? new Date(value).toLocaleString() : '—';

function App() {
  const [items, setItems] = useState([]); const [tab, setTab] = useState('pending'); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [toast, setToast] = useState(''); const [refreshed, setRefreshed] = useState(null); const [rejecting, setRejecting] = useState(null); const [reason, setReason] = useState(''); const [note, setNote] = useState('');
  const load = async () => { setError(''); try { const r = await fetch('/api/submissions'); if (!r.ok) throw new Error(); const data = await r.json(); setItems(data.submissions || []); setRefreshed(data.refreshedAt); } catch { setError('Could not reach Mango Habanero. Check the backend terminal and retry.'); } };
  useEffect(() => { load(); }, []); useEffect(() => { if (toast) { const t = setTimeout(() => setToast(''), 3000); return () => clearTimeout(t); } }, [toast]);
  const visible = useMemo(() => items.filter((x) => statusForTab(tab, x)).sort((a,b) => new Date(b.created_at)-new Date(a.created_at)), [items, tab]);
  const act = async (id, url, options = {}) => { setBusy(id); setError(''); try { const r = await fetch(url, { method: options.method || 'POST', headers: {'Content-Type':'application/json'}, body: options.body ? JSON.stringify(options.body) : undefined }); const data = await r.json(); if (!r.ok) throw new Error(data.error || 'Action failed'); await load(); setToast(options.toast || 'Saved.'); } catch (e) { setError(e.message); } finally { setBusy(''); } };
  const approve = (id) => act(id, `/api/submissions/${id}/review`, {body:{action:'approve'},toast:'Approved for the next Jalapeño publishing run.'});
  const reject = async () => { if (!reason) return; const id = rejecting; setRejecting(null); await act(id, `/api/submissions/${id}/review`, {body:{action:'reject',reasonCategory:reason,reviewerNote:note},toast:'Rejected with an audit reason.'}); setReason(''); setNote(''); };
  const counts = Object.fromEntries(tabs.map(([key]) => [key, items.filter((x) => statusForTab(key,x)).length])); const priority = items.find((x) => x.is_publish_priority && x.status === 'approved' && !x.featured_at);
  return <div className="app"><header><div className="brand-mark">🔥</div><div><p className="eyebrow">BUFFAGO / INTERNAL REVIEW</p><h1>Mango Habanero</h1><p className="subtitle">Human moderation & publishing priority for Wing Shots</p></div><button className="refresh" onClick={load}>↻ Refresh</button></header>
    <main><section className="statusbar"><div><strong>Review desk</strong><span className="muted">Private media · service-authorized previews</span></div><span className="last">{refreshed ? `Last refreshed ${formatDate(refreshed)}` : 'Loading queue…'}</span></section>
      <nav>{tabs.map(([key,label]) => <button key={key} className={tab===key?'active':''} onClick={() => setTab(key)}>{label}<span>{counts[key]}</span></button>)}</nav>
      {priority && <div className="priority-banner"><span>⚡ Priority: Next Jalapeño Run</span><strong>{priority.restaurant?.name || 'Selected submission'}</strong><button onClick={() => act(priority.submission_id, `/api/submissions/${priority.submission_id}/priority`, {method:'DELETE',toast:'Priority cleared.'})} disabled={!!busy}>Clear Priority</button></div>}
      {error && <div className="error"><strong>Something needs attention.</strong> {error}<button onClick={load}>Retry</button></div>}
      {!error && !visible.length && <div className="empty"><div>🌶️</div><h2>Nothing in {tabs.find((x)=>x[0]===tab)?.[1]}</h2><p>New Wing Shots and completed reviews will appear here.</p></div>}
      <div className="grid">{visible.map((item) => <Card key={item.submission_id} item={item} tab={tab} busy={busy===item.submission_id} approve={approve} reject={() => {setRejecting(item.submission_id);setReason('');setNote('')}} prioritize={() => act(item.submission_id, `/api/submissions/${item.submission_id}/priority`, {toast:'Marked as the next Jalapeño priority.'})} />)}</div>
    </main>{rejecting && <div className="modal-backdrop"><div className="modal"><h2>Reject Wing Shot</h2><p>Select the reason that best explains the decision.</p><select value={reason} onChange={(e)=>setReason(e.target.value)}><option value="">Choose a reason…</option>{reasons.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><textarea value={note} onChange={(e)=>setNote(e.target.value)} placeholder="Optional reviewer note" maxLength="2000"/><div className="modal-actions"><button className="quiet" onClick={()=>setRejecting(null)}>Cancel</button><button className="danger" disabled={!reason} onClick={reject}>Confirm rejection</button></div></div></div>}{toast && <div className="toast">✓ {toast}</div>}</div>;
}
function Card({item,tab,busy,approve,reject,prioritize}) { const [url,setUrl]=useState(''); const [previewBusy,setPreviewBusy]=useState(false); const preview=async()=>{setPreviewBusy(true);try{const r=await fetch(`/api/submissions/${item.submission_id}/preview`,{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error);setUrl(d.url);}catch(e){alert(e.message)}finally{setPreviewBusy(false)}}; const media=url ? (item.media_type==='video'?<video controls autoPlay src={url}/>:<img src={url} alt="Wing Shot preview"/>) : <button className="preview-placeholder" onClick={preview}>{previewBusy?'Generating private preview…':'▶ Load private preview'}</button>; return <article className={`card ${item.is_publish_priority?'selected':''}`}><div className="media">{media}</div><div className="card-body"><div className="card-head"><div><span className="pill">{item.media_type}</span><span className="state">{item.status}</span><h2>{item.restaurant?.name || 'Unknown restaurant'}</h2><p>{[item.restaurant?.city,item.restaurant?.state_code].filter(Boolean).join(', ') || 'Location unavailable'}</p></div>{item.is_publish_priority&&<span className="priority-label">⚡ NEXT</span>}</div><dl><dt>Submission</dt><dd>{item.submission_id}</dd><dt>Rating ID</dt><dd>{item.rating_id}</dd><dt>Contributor</dt><dd>{item.contributor?.username || item.contributor?.user_id || 'Anonymous'}</dd><dt>Uploaded</dt><dd>{formatDate(item.created_at)}</dd><dt>Attribution</dt><dd>{item.attribution_preference || '—'}</dd></dl><p className="caption">{item.caption || 'No caption provided.'}</p>{item.ai_moderation&&<div className="advisory"><strong>AI assistance:</strong> {item.ai_moderation.recommendation || '—'}{item.ai_moderation.explanation&&` · ${item.ai_moderation.explanation}`}</div>}{item.processing?.some((x)=>x.last_error_code)&&<div className="warning">⚠ Processing warning: {item.processing.find((x)=>x.last_error_code)?.last_error_code}</div>}<div className="actions">{tab==='pending'&&<><button className="approve" disabled={busy} onClick={()=>approve(item.submission_id)}>{busy?'Saving…':'Approve'}</button><button className="reject" disabled={busy} onClick={reject}>Reject</button></>}{tab==='approved'&&<button className="approve" disabled={busy||item.is_publish_priority} onClick={prioritize}>{item.is_publish_priority?'Priority set':'Make Next'}</button>}{tab==='rejected'&&<span className="muted">Rejected {formatDate(item.rejected_at)}</span>}{tab==='posted'&&<span className="muted">Posted {formatDate(item.featured_at)}</span>}</div></div></article> }

createRoot(document.getElementById('root')).render(<App/>);
