'use strict';
let state={}, csrf='', busy=false, loaded=false;
const $=id=>document.getElementById(id), text=(id,value)=>{$(id).textContent=value??'—';};
function feedback(message,error=false){text('feedback',message);$('feedback').classList.toggle('error',error);}
async function api(path,body){const response=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body),credentials:'same-origin',cache:'no-store'});let value;try{value=await response.json();}catch{throw Error('The Pi returned an invalid response.');}if(!response.ok){throw Error(value.error||'Request failed.');}return value;}
async function task(work){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await work();}catch(e){feedback(e instanceof TypeError?'Cannot reach the Pi. Check Wi-Fi and try again.':e.message,true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function tab(name){document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==name);document.querySelectorAll('nav button').forEach(b=>{if(b.dataset.tab===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
function render(){const g=state.growth_os||{},n=g.north_star||{},e=g.current_experiment||{},m=g.todays_move||{},i=g.marketing_insight||{},b=g.founder_balance_7d||{};text('mau',`${n.current??'—'} / ${e.target_value??'—'} target`);const pct=Number(e.target_value)>0?Number(n.current||0)/Number(e.target_value)*100:0;$('progress').value=Math.max(0,Math.min(100,pct));text('previous',`Previous 30 days: ${n.previous_30d??'—'}`);text('overview-move',m.title||'No move set');text('overview-move-status',m.status||'');text('move-summary',[m.title,m.why_it_matters,m.status].filter(Boolean).join(' · '));let days='';if(e.start_date&&e.end_date){const start=new Date(e.start_date+'T00:00:00'),end=new Date(e.end_date+'T00:00:00');const duration=Math.round((end-start)/86400000)+1;const day=Math.max(0,Math.min(duration,Math.floor((new Date()-start)/86400000)+1));days=` · Day ${day} / ${duration}`;}text('overview-experiment',(e.title||'No active experiment')+days);text('experiment-summary',[e.title,e.hypothesis,e.status].filter(Boolean).join(' · ')+days);text('overview-insight',i.title||'No current insight');text('insight-title',i.title||'No current insight');text('insight-body',i.body||'');text('insight-source',i.source||'');document.querySelectorAll('.balance').forEach(el=>el.textContent=`Product ${b.product??0} · Growth ${b.growth??0} · Customer ${b.customer??0}`);document.querySelectorAll('.audit').forEach(list=>{list.replaceChildren();(state.recent_audit||[]).slice(0,5).forEach(event=>{const item=document.createElement('li');item.textContent=`${String(event.action||'Activity').replaceAll('_',' ')} · ${event.created_at?new Date(event.created_at).toLocaleString():''}`;list.append(item);});if(!list.children.length){const item=document.createElement('li');item.textContent='No recent activity';list.append(item);}});text('freshness','Updated '+new Date().toLocaleTimeString());}
async function refresh(){state=await api('/api/state');csrf=state.csrf;loaded=true;render();}
async function write(action,data,confirmed=false){await api('/api/action',{action,data,...(confirmed?{confirmed:true}:{})});feedback('Saved. The wall display will update on its next refresh.');try{await refresh();}catch(e){feedback('Saved, but refreshed state is unavailable. '+e.message,true);}}
function fields(form){return Object.fromEntries(new FormData(form));}
function entity(key){const value=state.growth_os?.[key];if(!value?.id)throw Error('No current item. Refresh or create one first.');return value.id;}
$('refresh').onclick=()=>task(async()=>{await refresh();feedback('State refreshed.');});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{tab('activity');$('activity-form').elements.category.value=b.dataset.category;$('activity-form').elements.description.focus();});
document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>task(()=>write('set_move_status',{id:entity('todays_move'),status:b.dataset.move})));
$('experiment-form').onsubmit=event=>{event.preventDefault();task(()=>{if(!confirm('Create this experiment and replace the active experiment?'))return;const data=fields(event.target);data.target_value=Number(data.target_value);return write('set_experiment',data);});};
$('target-form').onsubmit=event=>{event.preventDefault();task(()=>write('update_experiment_progress',{id:entity('current_experiment'),target_value:Number(fields(event.target).target_value)}));};
$('close-form').onsubmit=event=>{event.preventDefault();task(()=>{const data={id:entity('current_experiment'),status:fields(event.target).status};if(confirm(`Close this experiment as ${data.status}?`))return write('close_experiment',data,true);});};
$('move-form').onsubmit=event=>{event.preventDefault();task(()=>{const now=new Date(),date=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');return write('set_move',{...fields(event.target),date});});};
$('activity-form').onsubmit=event=>{event.preventDefault();task(async()=>{await write('log_activity',{...fields(event.target),source:'mobile_control'});event.target.elements.description.value='';});};
$('insight-form').onsubmit=event=>{event.preventDefault();task(()=>{const data=fields(event.target);data.expires_at=data.expires_at?new Date(data.expires_at).toISOString():null;return write('publish_insight',data);});};
$('expire').onclick=()=>task(()=>{if(confirm('Expire the current insight?'))return write('expire_insight',{id:entity('marketing_insight')});});
// Fetch on page load, manual Refresh, and successful writes.
task(async()=>{await refresh();feedback('State refreshed.');});

// Populate edit forms on successful state refresh; never refresh while typing.
const originalRender=render;
render=function(){originalRender();const g=state.growth_os||{};for(const [id,key] of [['experiment-form','current_experiment'],['move-form','todays_move'],['insight-form','marketing_insight']]){const data=g[key]||{};const form=$(id);for(const element of form.elements){if(!element.name||element.name==='expires_at')continue;if(element.name==='metric_name'){element.value='mau_30d';continue;}if(data[element.name]!=null)element.value=data[element.name];}}if(g.current_experiment?.target_value!=null)$('target-form').elements.target_value.value=g.current_experiment.target_value;};