-- Phase7B.3D: full ledger-row and column-ACL drift. Only run remotely in an approved change window; local fixture verification only.
begin read only; set local search_path=pg_catalog,public; select md5((jsonb_build_object(
 'database',current_database(),'user',current_user,'session',session_user,
 'version',current_setting('server_version_num'),
 'ledger',(select coalesce(jsonb_agg(jsonb_build_array(m.version,m.name,md5(coalesce(m.statements::text,'')),md5(to_jsonb(m)::text)) order by m.version),'[]'::jsonb) from supabase_migrations.schema_migrations m),
 'roles',(select jsonb_agg(jsonb_build_array(rolname,rolsuper,rolinherit,rolcreaterole,rolcreatedb,rolcanlogin,rolreplication,rolbypassrls,rolconfig) order by rolname) from pg_roles),
 'members',(select coalesce(jsonb_agg(jsonb_build_array(roleid::regrole::text,member::regrole::text,grantor::regrole::text,admin_option,inherit_option,set_option) order by roleid::regrole::text,member::regrole::text,grantor::regrole::text),'[]'::jsonb) from pg_auth_members),
 'schemas',(select jsonb_agg(jsonb_build_array(nspname,nspowner::regrole::text,nspacl::text) order by nspname) from pg_namespace where nspname in ('public','private','auth','storage','supabase_migrations')),
 'defaults',(select coalesce(jsonb_agg(jsonb_build_array(defaclrole::regrole::text,defaclnamespace,defaclobjtype,defaclacl::text) order by defaclrole,defaclnamespace,defaclobjtype),'[]'::jsonb) from pg_default_acl),
 'relations',(select jsonb_agg(jsonb_build_array(n.nspname,c.relname,c.relkind,c.relowner::regrole::text,c.relrowsecurity,c.relforcerowsecurity,c.relacl::text) order by n.nspname,c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private','auth','storage','supabase_migrations') and c.relkind in ('r','p','v','m','S','f')),
 'columns',(select jsonb_agg(jsonb_build_array(a.attrelid::regclass::text,a.attname,format_type(a.atttypid,a.atttypmod),a.attnotnull,a.attgenerated,pg_get_expr(d.adbin,d.adrelid),a.attacl::text) order by a.attrelid::regclass::text,a.attnum) from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname in ('public','private','auth','storage','supabase_migrations') and a.attnum>0 and not a.attisdropped),
 'constraints',(select jsonb_agg(jsonb_build_array(conrelid::regclass::text,conname,convalidated,pg_get_constraintdef(oid,true)) order by conrelid::regclass::text,conname) from pg_constraint where connamespace in (select oid from pg_namespace where nspname in ('public','private','auth','storage','supabase_migrations'))),
 'indexes',(select jsonb_agg(jsonb_build_array(i.indexrelid::regclass::text,i.indisvalid,i.indisready,pg_get_indexdef(i.indexrelid)) order by i.indexrelid::regclass::text) from pg_index i join pg_class c on c.oid=i.indrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private','auth','storage','supabase_migrations')),
 'triggers',(select jsonb_agg(jsonb_build_array(t.tgrelid::regclass::text,t.tgname,t.tgenabled,pg_get_triggerdef(t.oid,true)) order by t.tgrelid::regclass::text,t.tgname) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where not t.tgisinternal and n.nspname in ('public','private','auth','storage','supabase_migrations')),
 'functions',(select jsonb_agg(jsonb_build_array(p.oid::regprocedure::text,p.proowner::regrole::text,p.prosecdef,p.provolatile,p.proconfig,p.proacl::text,md5(p.prosrc),p.prorettype::regtype::text,p.proallargtypes,p.proargmodes,p.proargnames,p.prolang,p.prokind) order by p.oid::regprocedure::text) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private','auth','storage','supabase_migrations')),
 'rules',(select coalesce(jsonb_agg(jsonb_build_array(ev_class::regclass::text,rulename,md5(pg_get_ruledef(oid,true))) order by ev_class::regclass::text,rulename),'[]'::jsonb) from pg_rewrite),
 'event_triggers',(select coalesce(jsonb_agg(jsonb_build_array(evtname,evtevent,evtowner::regrole::text,evtfoid::regprocedure::text,evtenabled,evttags,md5(p.prosrc),p.proconfig,p.proacl::text) order by evtname),'[]'::jsonb) from pg_event_trigger e join pg_proc p on p.oid=e.evtfoid),
 'policies',(select coalesce(jsonb_agg(jsonb_build_array(polrelid::regclass::text,polname,polcmd,polpermissive,polroles,pg_get_expr(polqual,polrelid),pg_get_expr(polwithcheck,polrelid)) order by polrelid::regclass::text,polname),'[]'::jsonb) from pg_policy)
))::text); rollback;
